cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'coreutils'
brew 'docker-clean'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'git'
brew 'hub'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# cask '1password'
# cask 'dropbox'
cask 'font-meslo-lg-for-powerline'
# cask 'google-chrome'
# cask 'iterm2'
# cask 'slack'
# cask 'steam'
# cask 'vlc'

